### PR TITLE
set the platform version automatically during build

### PR DESCRIPTION
**Pull request by fs111**
The platform version shows up in driven, so it is a good idea to have it correct. This PR uses maven resource filtering, to make sure it is always up2date.

### CODE REVIEW

**Comment by fs111** [comment]
@fhueske just back from vacation. Going to take a look.

**Comment by fs111** [comment]
@fhueske this is a problem with the way resources are handled in maven. Turns out one cannot just filter the files in src/main/java. I may be able to provide a better solution before 0.3, if time permits.

**Comment by fhueske** [comment]
Thanks for taking a look @fs111. In case we do not find a solution, we can simply hard-code the version for the next release.

**Comment by fs111** [comment]
@fhueske here is a version that works. maven resource plugin filters a properties file and that is read at runtime. I verified that the correct version shows up in driven.

**Comment by fhueske** [comment]
Thanks a lot @fs111!
I merged this PR.

**Pull request closed without merging**
